Repository nextcloud/twofactor_webauthn, pull requests merged in 2022-06, with the labels that each got.

#187 Add PHP8.1 + 8.2 lint job
  .github/workflows/lint.yml
Labels: 3. to review

#200 Add missing changes to package-lock.json
  package-lock.json
Labels: techdebt, 4. to release

#199 Rename "WebAuthn device" to "security key" in the UI
  lib/Activity/Setting.php
  lib/Provider/WebAuthnProvider.php
  src/components/AddDeviceDialog.vue
  src/components/Challenge.vue
  src/components/Device.vue
  src/components/LoginSetup.vue
  src/components/PersonalSettings.vue
  src/tests/components/Device.spec.js
  src/tests/components/PersonalSettings.spec.js
  tests/Unit/Activity/SettingTest.php
  tests/Unit/Provider/WebAuthnProviderTest.php
Labels: 4. to release

#201 Reoder device actions
  src/components/Device.vue
Labels: 3. to review

#203 Hide registration abort error
  src/components/AddDeviceDialog.vue
Labels: bug, 3. to review
