Repository nextcloud/twofactor_webauthn, pull requests merged in 2022-03, with the labels that each got.

#92 Implement command to migrate u2f registrations to webauthn
  appinfo/info.xml
  lib/Command/MigrateU2F.php
  lib/Db/Registration.php
  lib/Db/RegistrationMapper.php
  lib/Service/U2FMigrator.php
  lib/Service/WebAuthnManager.php
  src/components/Challenge.vue
  tests/Unit/Service/WebAuthnManagerTest.php
Labels: enhancement

#132 Scope cs-fixer to avoid dependency hell
  .gitignore
  composer.json
  composer.lock
  tests/psalm-baseline.xml
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: bug

#135 Add integration/installation tests on CI
  .github/workflows/test.yml
Labels: enhancement

#138 Fix icon in darkmode
  css/style.css
Labels: bug

#139 Document how to migrate from U2F
  README.md
Labels: enhancement, documentation

#140 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#141 Make the composer bin plugin a production dep
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.lock
Labels: bug
