Repository nextcloud/twofactor_webauthn, pull requests merged in 2022-10, with the labels that each got.

#204 Store and show key creation time
  appinfo/info.xml
  lib/Command/MigrateU2F.php
  lib/Db/PublicKeyCredentialEntity.php
  lib/Db/PublicKeyCredentialEntityMapper.php
  lib/Migration/Version010000Date20220929073925.php
  lib/Repository/WebauthnPublicKeyCredentialSourceRepository.php
  lib/Service/WebAuthnManager.php
  package-lock.json
  package.json
  src/components/Device.vue
  src/components/PersonalSettings.vue
  src/tests/setup.js
Labels: enhancement, 3. to review

#261 Adjust testing matrix for Nextcloud 25 on main
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 4. to release

#278 Fix device icon with dark theme
  src/components/Device.vue
Labels: 3. to review, backport-request
