Repository nextcloud/twofactor_webauthn, pull requests merged in 2022-09, with the labels that each got.

#254 Cleanup WebAuthn data on user delete
  lib/AppInfo/Application.php
  lib/Db/PublicKeyCredentialEntityMapper.php
  lib/Listener/UserDeleted.php
  tests/psalm-baseline.xml
Labels: 3. to review

#144 Add repair step to migrate old 2FA provider registrations
  .github/workflows/test.yml
  appinfo/info.xml
  composer.json
  lib/Migration/RepairProviderRegistrations.php
  tests/Integration/Migration/RepairProviderRegistrationsTest.php
Labels: bug, 3. to review, regression

#255 Command to remove orphaned webauthn credentials
  appinfo/info.xml
  lib/Command/CleanUp.php
  lib/Db/PublicKeyCredentialEntityMapper.php
  lib/Listener/UserDeleted.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review

#260 Drop Nextcloud 22-24 support
  .github/workflows/lint.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#257 Center login buttons
  src/components/Challenge.vue
Labels: enhancement, 3. to review

#256 Fix white login icon on white background
  templates/challenge.php
Labels: 3. to review, blocked

#224 Show twofactor icon and short description on login setup page
  src/components/LoginSetup.vue
  templates/login-setup.php
Labels: enhancement, 4. to release, design

#210 Remove click from sign in
  src/components/Challenge.vue
Labels: enhancement, 4. to release

#264 [stable0.3] Add repair step to migrate old 2FA provider registrations
  appinfo/info.xml
  composer.json
  lib/Migration/RepairProviderRegistrations.php
  tests/Integration/Migration/RepairProviderRegistrationsTest.php
Labels: 3. to review
