Repository nextcloud/twofactor_webauthn, pull requests merged in 2022-12, with the labels that each got.

#309 fix(challenge): invert icon based on theme
  css/challenge.css
  templates/challenge.php
Labels: bug, 4. to release, design, backport-request

#312 chore: Use conventional commits
  .github/dependabot.yml
  .github/workflows/conventional_commits.yml
Labels: 3. to review

#319 ci: Migrate to the new OCP package for static analysis
  .github/workflows/static-analysis.yml
Labels: 3. to review

#313 chore: Drop noop Dependabot configs
  .github/dependabot.yml
Labels: techdebt, 3. to review
