Repository nextcloud/twofactor_webauthn, pull requests merged in 2023-11, with the labels that each got.

#474 chore(release): v1.3.0-alpha1
  CHANGELOG.md
Labels: 3. to review

#477 [stable1.2] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#478 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#481 ci: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
Labels: 3. to review

#482 fix: allow users to toggle their devices
  lib/Controller/SettingsController.php
Labels: bug, 3. to review

#483 fix: handle devices by their db entity id
  lib/Controller/SettingsController.php
  lib/Db/PublicKeyCredentialEntityMapper.php
  lib/Service/WebAuthnManager.php
  src/components/Device.vue
  src/components/PersonalSettings.vue
  src/store.js
  tests/Unit/Service/WebAuthnManagerTest.php
Labels: bug, 4. to release

#484 fix: drop support for nextcloud 25 and php 7.4
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
  appinfo/info.xml
  composer.json
Labels: 3. to review

#489 Add support for PHP 8.3 and Nextcloud 29
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: enhancement, 3. to review, backport-request

#495 chore: bump @nextcloud/vue to 8.2.0 and peers
  package-lock.json
  package.json
Labels: dependencies, 4. to release
