Repository nextcloud/twofactor_webauthn, pull requests merged in 2023-02, with the labels that each got.

#349 feat: drop php 7.4 and add support for 8.2
  .github/workflows/lint.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: techdebt, 4. to release

#348 chore: refactor challenge component
  src/components/Challenge.vue
  src/tests/utils/base64.spec.js
  src/utils/base64.js
Labels: techdebt, 4. to release

#350 v1.1.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#351 chore: main is now v1.2.0-alpha.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#279 Fix form element alignment of new device dialog
  package-lock.json
  package.json
  src/components/AddDeviceDialog.vue
Labels: bug, 4. to release, design, backport-request

#323 Fix key registration
  appinfo/info.xml
  lib/Migration/Version010000Date20221227080000.php
Labels: bug, 4. to release, backport-request

#357 v1.1.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#358 chore: forward port changelog from v1.1.1
  CHANGELOG.md
Labels: 3. to review
