Repository nextcloud/twofactor_webauthn, pull requests merged in 2023-10, with the labels that each got.

#444 chore: replace dependabot with renovate
  .github/dependabot.yml
  .github/workflows/dependabot-approve-merge.yml
  renovate.json
Labels: 3. to review

#465 [stable1.2] Fix CI
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
  composer.json
  composer.lock
  lib/Listener/UserDeleted.php
  tests/psalm-baseline.xml
Labels: 4. to release

#457 [stable1.2] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
