Repository nextcloud/twofactor_webauthn, pull requests merged in 2024-08, with the labels that each got.

#625 chore(composer): require psr/log:^1
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#623 fix: adjust personal settings to compact design
  src/components/Device.vue
Labels: bug, 3. to review, design

#598 [stable1.4] Fix npm audit
  package-lock.json
Labels: dependencies, 4. to release

#621 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#608 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
Labels: dependencies, 4. to release, automated

#628 feat(deps): Add Nextcloud 31 support
  appinfo/info.xml
  package-lock.json
  package.json
Labels: enhancement, 4. to release

#631 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#632 [stable1.4] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#635 ci(npm-audit-fix): run on stable2.0
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#636 [stable2.0] ci(test): run on server stable30
  .github/workflows/test.yml
Labels: 3. to review

#637 [stable2.0] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#642 [stable2.0] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#641 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#638 chore: Removed unused deprecated `ILogger`
  lib/Activity/Provider.php
  tests/Unit/Activity/ProviderTest.php
Labels: techdebt, 3. to review

#640 [stable1.4] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
