Repository nextcloud/twofactor_webauthn, pull requests merged in 2024-04, with the labels that each got.

#565 feat: add support for Nextcloud 30 and drop support for Nextcloud 26
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 3. to review

#568 ci(test): drop php 8.0
  .github/workflows/test.yml
Labels: 3. to review

#569 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#571 [stable1.4] ci: adjust test and psalm matrices to stable29
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
Labels: 3. to review

#572 ci: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
Labels: 3. to review

#570 [stable1.4] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#577 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies
