Repository nextcloud/twofactor_webauthn, pull requests merged in 2024-02, with the labels that each got.

#521 Update npm and node engines versions
  package.json
Labels: dependencies

#532 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm-matrix.yml
Labels: dependencies, 3. to review, automated

#534 chore: bump npm to ^10.0.0 in engines
  package-lock.json
Labels: 3. to review

#539 test: implement frontend e2e testing using playwright
  .github/workflows/test.yml
  .gitignore
  .nextcloudignore
  package-lock.json
  package.json
  playwright.config.js
  src/tests/e2e/loggedin.setup.js
  src/tests/e2e/login-setup.spec.js
  src/tests/e2e/occ.js
  src/tests/e2e/settings.loggedin.spec.js
  src/tests/e2e/virtualAuthenticator.js
  src/tests/unit/components/Device.spec.js
  src/tests/unit/components/PersonalSettings.spec.js
  src/tests/unit/setup.js
  src/tests/unit/utils/base64.spec.js
Labels: 3. to review

#543 chore: cleanup webpack config
  babel.config.js
  package-lock.json
  package.json
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
  src/webpack.test.js
  templates/challenge.php
  templates/login-setup.php
  templates/personal.php
  webpack.config.js
  webpack.test.config.js
Labels: techdebt, 3. to review

#544 chore: refactor promises to async/await
  src/components/AddDeviceDialog.vue
Labels: techdebt, 3. to review
