Repository nextcloud/twofactor_webauthn, pull requests merged in 2024-10, with the labels that each got.

#660 [stable1.4] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#671 [stable2.0] fix(deps): bump psr/log to ^2
  composer.json
  composer.lock
Labels: bug, techdebt, 3. to review

#666 [stable2.0] Fix npm audit
  package-lock.json
Labels: dependencies, 4. to release

#670 fix(deps): bump psr/log to ^2|^3
  .github/workflows/psalm-matrix.yml
  composer.json
  composer.lock
Labels: bug, techdebt, 3. to review

#665 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#681 chore: fix db types
  lib/Db/PublicKeyCredentialEntity.php
  lib/Db/Registration.php
Labels: techdebt, 3. to review
