Repository nextcloud/twofactor_webauthn, pull requests merged in 2025-08, with the labels that each got.

#827 fix(db): match ID and user handle
  lib/Db/PublicKeyCredentialEntityMapper.php
  lib/Service/WebAuthnManager.php
  tests/Unit/Service/WebAuthnManagerTest.php
Labels: bug, 3. to review, backport-request

#831 chore(release): v2.2.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#820 [stable2.2] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#838 [stable2.2] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#837 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 4. to release

#839 [stable2.3] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#840 chore(release): v2.3.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
