Repository nextcloud/twofactor_webauthn, pull requests merged in 2025-04, with the labels that each got.

#759 ci(test): add summary job
  .github/workflows/test.yml
Labels: 3. to review, backport-request

#762 chore: move psalm to vendor-bin
  REUSE.toml
  composer.json
  composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: dependencies, techdebt, 3. to review

#745 chore(vue3): migrate from vuex to pinia
  package-lock.json
  package.json
  src/components/AddDeviceDialog.vue
  src/components/Challenge.vue
  src/components/Device.vue
  src/components/PersonalSettings.vue
  src/main-challenge.js
  src/main-login-setup.js
  src/main-settings.js
  src/store.js
  src/tests/unit/components/Device.spec.js
  src/tests/unit/components/PersonalSettings.spec.js
Labels: techdebt, 3. to review

#766 [stable2.1] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
