Repository nextcloud/twofactor_webauthn, pull requests merged in 2025-01, with the labels that each got.

#716 [stable2.1] feat: support for php 8.4
  .github/workflows/test.yml
  appinfo/info.xml
Labels: enhancement, 3. to review

#714 chore(CI): Adjust testing matrix for Nextcloud 31 on main
  .github/workflows/test.yml
Labels: 4. to release

#717 chore(release): v2.1.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#718 [stable2.1] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#694 [stable1.4] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#696 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
