Repository nextcloud/twofactor_webauthn, pull requests merged in 2025-05, with the labels that each got.

#771 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#772 [stable2.1] Fix npm audit
  package-lock.json
Labels: dependencies, 4. to release

#779 ci(npm-audit-fix): stable1.4 is eol
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#784 fix: activating and deactivating devices
  src/components/Device.vue
  src/tests/e2e/settings.spec.js
Labels: bug, 3. to review, regression

#781 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#788 [stable2.2] chore(release): v2.2.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#791 chore(deps): use logical or to limit version range of psr/log
  composer.json
  composer.lock
Labels: dependencies, 3. to review
